name: 'Terraform Module Test'

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tf-test:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8
        with:
          terraform_version: ${{ vars.TF_VERSION_LATEST }}
          terraform_wrapper: false
      - name: terraform_test
        env:
            TF_VAR_org_id: ${{ vars.MONGODB_ATLAS_ORG_ID }}
            MONGODB_ATLAS_BASE_URL: ${{ vars.MONGODB_ATLAS_BASE_URL }}
            MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
            MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }} 
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
            cd ./modules/s3_bucket
            terraform init
            terraform test
